name: ReviveMe
version: '1.0'
main: pl.Dowimixworsafe.reviveMe.ReviveMe
api-version: '1.21'
commands:
  reviveme:
    description: Manages the revival system.
    usage: /reviveme <nick> | set <lang/mode/time/mob/fly/glow/tag/haunt/haunt-delay> | reload
permissions:
  reviveme.admin:
    description: Allows access to administrator commands.
    default: op