name: ReviveRitual
version: '1.0'
main: pl.Dowimixworsafe.reviveRitual.ReviveRitual
api-version: '1.21'
commands:
  rr:
    description: Manages the revival system.
    usage: /rr <nick> | set <lang/mode/time/mob/fly/glow/tag/haunt/haunt-delay> | reload
permissions:
  reviveme.admin:
    description: Allows access to administrator commands.
    default: op